<a href="https://colab.research.google.com/github/rushikeshpatil-123/DataScience_Analytics/blob/main/pandas_pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd

In [45]:
# 1D
array =pd.Series(np.arange(1,10,1))
# 2D : Multi Dimensional
array1 = pd.DataFrame({
    "Name":[np.nan, "Tathagat","Rushikesh","Shivam","Sanjeev",np.nan],
    "CGPA":[10,8,9,np.nan,np.nan,9],
    "Salary":[1000,2000,3000,4000,5000,6000],
    "Age":[19,21,23,25,27,29]
})

In [46]:
# Checking Descriptive stats
array1.describe()

            CGPA       Salary        Age
count   4.000000     6.000000   6.000000
mean    9.000000  3500.000000  24.000000
std     0.816497  1870.828693   3.741657
min     8.000000  1000.000000  19.000000
25%     8.750000  2250.000000  21.500000
50%     9.000000  3500.000000  24.000000
75%     9.250000  4750.000000  26.500000
max    10.000000  6000.000000  29.000000

In [47]:
numerical_col = array1.select_dtypes(exclude = 'object')
categorical_col = array1.select_dtypes(include = 'object')

from collections import OrderedDict
def descriptive_stats():    # Function Defination
  stats = []
  for i in numerical_col.columns:
      numerical_stats = OrderedDict({
          "Feature": i,
          "Count":array1[i].count(),
          "Mean":array1[i].mean(),
          "Std":array1[i].std(),
          "Min":array1[i].min(),
          "Max":array1[i].max(),
          "25%":array1[i].quantile(0.25),
          "50%":array1[i].quantile(0.50),
          "75%":array1[i].quantile(0.75),
          "IQR":array1[i].quantile(0.75)-array1[i].quantile(0.25),
          "Skewness":array1[i].skew(),
          "Kurtosis":array1[i].kurtosis()

      })

      stats.append(numerical_stats)
      report = pd.DataFrame(stats)
  return report

data_info = descriptive_stats()    # Function Calling
print(data_info)

  Feature  Count    Mean          Std     Min     Max      25%     50%  \
0    CGPA      4     9.0     0.816497     8.0    10.0     8.75     9.0
1  Salary      6  3500.0  1870.828693  1000.0  6000.0  2250.00  3500.0
2     Age      6    24.0     3.741657    19.0    29.0    21.50    24.0

       75%     IQR  Skewness  Kurtosis
0     9.25     0.5       0.0       1.5
1  4750.00  2500.0       0.0      -1.2
2    26.50     5.0       0.0      -1.2

In [48]:
# Checking Dataset Information
array1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   CGPA    4 non-null      float64
 2   Salary  6 non-null      int64
 3   Age     6 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 324.0+ bytes

In [49]:
# CGPA : 04/06: Missing value percentage : 0.33
# Imputation statergies (Fill Null Values): Mean, Medain, Mode , Constant Value

array1["CGPA"] = array1["CGPA"].fillna(array1["CGPA"].median())

In [50]:
# Checking Dataset Information

array1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   CGPA    6 non-null      float64
 2   Salary  6 non-null      int64
 3   Age     6 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 324.0+ bytes

In [51]:
array1["Name"]= array1["Name"].fillna(array1["Name"].mode())

In [52]:
# checking dataset information
array1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   CGPA    6 non-null      float64
 2   Salary  6 non-null      int64
 3   Age     6 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 324.0+ bytes

In [53]:
array1

        Name  CGPA  Salary  Age
0  Rushikesh  10.0    1000   19
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5        NaN   9.0    6000   29

In [54]:
array1["Name"]= array1["Name"].fillna("Dadu")

In [55]:
array1

        Name  CGPA  Salary  Age
0  Rushikesh  10.0    1000   19
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29

In [56]:
data1 = pd.DataFrame({
    "Name": [np.nan,"Thatagat",np.nan,"Akshay","Vishal"],
    "Age": [100,22,300,np.nan,np.nan]
})
data1

       Name    Age
0       NaN  100.0
1  Thatagat   22.0
2       NaN  300.0
3    Akshay    NaN
4    Vishal    NaN

In [57]:
data1["Name"]= data1["Name"].fillna(data1["Name"].mode())

data1

       Name    Age
0    Akshay  100.0
1  Thatagat   22.0
2    Vishal  300.0
3    Akshay    NaN
4    Vishal    NaN

In [58]:
array1.iloc[:3,1:]

   CGPA  Salary  Age
0  10.0    1000   19
1   8.0    2000   21
2   9.0    3000   23

In [59]:
array1

        Name  CGPA  Salary  Age
0  Rushikesh  10.0    1000   19
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29

In [60]:
x = array1.iloc[:,:3]
y = array1.iloc[:,3:]

In [61]:
x

        Name  CGPA  Salary
0  Rushikesh  10.0    1000
1   Tathagat   8.0    2000
2  Rushikesh   9.0    3000
3     Shivam   9.0    4000
4    Sanjeev   9.0    5000
5       Dadu   9.0    6000

In [62]:
y

   Age
0   19
1   21
2   23
3   25
4   27
5   29

In [63]:
# Using Drop()
array1

        Name  CGPA  Salary  Age
0  Rushikesh  10.0    1000   19
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29

In [64]:
X = array1.drop(columns='Age')
X

        Name  CGPA  Salary
0  Rushikesh  10.0    1000
1   Tathagat   8.0    2000
2  Rushikesh   9.0    3000
3     Shivam   9.0    4000
4    Sanjeev   9.0    5000
5       Dadu   9.0    6000

In [65]:
y  = array1["Age"]
y

0    19
1    21
2    23
3    25
4    27
5    29
Name: Age, dtype: int64

In [66]:
array1

        Name  CGPA  Salary  Age
0  Rushikesh  10.0    1000   19
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29

In [67]:
X = array1.drop(columns=['Name','Age'])

X

   CGPA  Salary
0  10.0    1000
1   8.0    2000
2   9.0    3000
3   9.0    4000
4   9.0    5000
5   9.0    6000

In [73]:
# Age > 20
array1[array1["Age"]> 20]

        Name  CGPA  Salary  Age
1   Tathagat   8.0    2000   21
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29

In [74]:
# CGPA = 9
array1[array1["CGPA"]==9]

        Name  CGPA  Salary  Age
2  Rushikesh   9.0    3000   23
3     Shivam   9.0    4000   25
4    Sanjeev   9.0    5000   27
5       Dadu   9.0    6000   29